language: python
python:
- '3.7'
before_install:
- echo $credentials.json > credentials.json
- echo google_compute_engine > /home/travis/.ssh/google_compute_engine
- chmod 0600 /home/travis/.ssh/google_compute_engine
install:
- pip3 install ansible>=2.4
- pip3 install molecule==2.22
- pip3 install apache-libcloud
- pip3 install testinfra==3.4.0
- pip3 install google-auth
- pip3 install google-api-python-client
script:
- molecule --debug create
