language: python
python:
- '3.7'
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xf secrets.tar
script:
- molecule create
- molecule list

env:
  global:
  - secure: ghHjMe+24jnet6EMLeLVvh1kPWHUdhEjWFeFTX6RujDzYkK396M5v79Xhd7MJ6AAu8arI26UmfraHwc/H+EY49CP8tD/CaHpFOO/ZuiVNCrQbvfVFNhH36n2OwU7dtI62yuEAq6EFULdbyTRCs4FNk24ZLw6F1JafSBe1A2mwtJE6FHybhP7EalUGltpL6pJ9I8h2XMrY29kv7CnzFx9fN8aAzRTcvOq7F9/kpk9plGwgwjFbQ2GDvV7MKnYQu+xqJBQkmw/xBoavPlRyAT/DIbeEZNDw/A/B8LoiWt9uP4FH3WBxlVw5fmcV99s9wXTvtH7DAXEzZLJ07HvwjoPovxDdIFlFZ25c+MNuXxKQwt+o6l5vn9zb9yMVd9WCMUNxO+jg697h/ZQVWKAhQiiciYoLWxiEuNvGhZG26cB9/PXSm/AntR3Tp2UL/1bB/tGaQavjN412vFVr+rGSwxV9Z4Tex0Z2JOntgUp5aPay6qMrGIsWlNrb+LmdmMdraRlsl1lKURYDM+PvQFNwYJun4rECvv6ANMPRNQJ00QS8eWHadS0mvSNp5ijJs6YscU2DwWdQsXY7gvSIGGDesUGsQQ3Aq6iYO70Vur10nLMXZhcAf96JCPWz26An7JcqAooBWCNvrhZfXQmz5KlNTD8nWBwUAlQObqdjHn7G+uZkyg=
  - secure: YXLZlIFKJXFgX6ZcAncwVP5+1cAUFogRABYg8JfaOhSun6tPgl94C+vDR4ifO9xaQTLRxkjdUdMIaNDlg6f98gszmNgVspaLzQyCX3MNUBqtcNO0J+KiCw7s5b98wZLNI+yUcliDwVyywYPU37doQobkiiDpcqXuaiqtTCwvydPmzEoKGOqLdEEumNYeBDaNzpUgUdloParKONKZkw0Iu/PZ6uX9lrP9LLTrbJrVXHul9n8W6r26g6wNeHjEYTsfvKBbquvTbw7DoMX4eGN1NTSCisBL9lsqdk1fjLdruPdmstuujCqZd7MoU5WFsMZ7E9oHsLm1vQgIez7DP4JOze/tbrPDIoCFqD37HpJdiQdctdg9Rt01ObLgzeaagCZFXJnf04tNGdL95Y7icSvhNktw8XbBCR8UE0fdSBkli58QjJQA/UcQ0a3qO2D7t6L9CVoKN2zvQPoOP3awlzkY9sLV63FPrlOsQWmYZlZboFX4RMOcQAvN4PHMxs8YsWppz/hR7Bt8l1a0B5dG5y0XJpNruXyM44ByJ0XQV7senuzkDw4IZvuEIArddjLk5bIEG32IUDna8W7lnH9lY4spwi6oYAgadxatd6O25oh1+LZe6HbogTPHEzXvqrsfI1M1vWNMiBCWFH1tYfSsFglPgbBslwHGmYGL+yhDAGsw3l8=
