language: python
python:
- '3.7'
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: yCnVtOul0JkWwoWNvZJ8n0wcBmNp2MCQXIjDSMS+HtIsFPjOsj+ADAsEA8Ql2tMrzi2wNAgBOXOyLTiUZ9Z7ExCfQBCjpVdxvl2sp7l4Qqt0u7p3SM1qylHk1EJMoS2iUkJC/SME1Exy8Be+ZU7vf9ETqfFIGmxMlhe3PA8uqGbhrN0ml1ntMAC1jpER7YmgkPiam8jyYJTwqPRHGRQGUk/VC/rp7mtPoLClPv+AX8nlx4AqnAHn3uM9Ae2qBLNp/HoqDVpLOi8yolVarZgx1GgxUvI14R4EI9orQnnDe6A9/Fy6vNVFGD9ksdm8UFxGn2HOcyxvW5oBqFb1pIPDHXfJulm7SMks6JseoJ3Xh4HstvvHWV14zOyR6cAX/UGDA6TaviW2hWR6Ldc/FhO1k4nOhs0onX3fArdZ2DjcWK8dg8DJiAgUyw9S4X5e7wmRYhY8t9BipCl1nTqA2JSAf9a9+u/xjW58WN1L5bIhz2CvAeRZZP7rreWREagdo4QZqFbTvuslv47Pc9xojnPOdCSDrgCVrZQwrxRC335W/NF22ROzrgriVJiCBoLxKpttalEsEKWc1COF1Ehueci0T+azeXBz+njSXyIkDnZhGeVyV4ORntFcvno1lBzQJvPIFVOFdHfQtDo8fM5nw+h68I1T30yHPQ4XPZJMUjF4Eyk=
  - secure: XDZa2DZTTGn/O/3Uzf1DwkZsYzp67q3szCntNz1wFRy1+hSKQbWBKgCQ+EIxse3OlG5UtKGT3e8+8CnnqZOLhdBnINGh686QQItS3/AGO/3kXKx2Ai2fkvMY8Ou6rFxsweL1Z7wZgYsNr1kXXufmsyJ6OAFH4dwWqTxPz81p+SpGfLfLmZruLNKLAUPhId62E5dOtdg65+13Bd3QKOGBbwXDKDPswSVicEo0ERg0bcUMQsE33FeYL/E3HLI+EoIW2bmlcONpDSf+/h40pO8rZuxIjB+6MXT8HuyrYlylX51kbdc+KYAuBDP3YTja2+h03uw0Hv4OMKDcRv8nKd5p6MV5eL2rEv0tY/wyBCbuPNx4N9tnWter2e+WNpBzFW1ni5vMz8Q27hNEmGCsUyX9ZK9bUK2RE053beVCS2SEmt76NDujJif1SXh7SLLeZ8/5Y7Mkel35njtQWTk0sQqWlAhUUuy3AdkadjRGwoMdQ9q8SyDz4bSLgQSLzevhJeHsCln9nFWXD2j5CapYQtArRIryyeRdJ1Iu8LJuF7lUwk0DOEl5sdsNM9UP1tGu054KFEMAOxEd3XegOYmUqsgsxLfKYu5DnRS24NJTlyGJH9C75LBmLW4mpsaNPHk4JPXfKxgLFaZQg458yOwwaKFyvv9UTO7bXbkYcINLXc6PDC8=
  - secure: cIWbi0mF8+OucpGX19C9vlQ5YB8EboBelkiHPPtXk9QXLjwYFXkHF333bDeSHUTewtYWAGoSqyH6C0Ai/YavyvcyVp8x7K85y1BfGtrLPYoFty8A3kSR/hSjrKsy/uJqGCPF5nZ7rmswrL0MzzQ+7Y8ceJCxldfigyjLkdEc8UpK+eFTQhf8fFq1JUI3nizxDgrw85DaMdeTYsGIt1Nb2ISm+Ov46RIFdC5fXQbu2I9gO9bBMdalgFxreK35MPPRnJfE3eQhdVzUSUdOPGF6i5hxvARKBDdcvBtYmYG1KBk9h0n0oscBbk8YOdyW+1MUXp5+mNxB7E6UALCWwdku3VcAjkonv/2AvYIVf4CqrEBbkzBaBuCXiKFDepAggeCFWt2tpcIvzdIged8OEeNnojTI7epMqVLjn3CbReqSZbjy552hcX3FnOjVdbaIF41uu3ueuF4hEkPKsBUDHgk1XNFbxubjB41Q5/OA/tSGdaUHNatl4nzXgHMjJcQwPRaAo06tE8rAmazlhS3LW2OpcT5cXTv3RsfSpdAFbL/+Ulm/FSXS9DdpA1D3VNJdu+/b/C6Zv1uugRDpnOs2YZOaf8Dsxcz5fzcEzbPV9GeCfZgjKS+7aT4IsS3EfKo0MU65nOOlz4c3rNu/SnrdtbMVdLTgdE1JrctE8n6ygtP5Bh4=
before_install:
- echo $super_secret_password
- openssl aes-256-cbc -k "$super_secret_password" -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
install:
- pip3 install ansible>=2.4
- pip3 install molecule==2.22
- pip3 install apache-libcloud
- pip3 install testinfra==3.4.0
- pip3 install google-auth
- pip3 install google-api-python-client
script:
- molecule --debug create
