---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: false
  vars:
    ssh_port: 22
    ssh_user: "travis"
    ssh_identity_file: "{{ lookup('env', 'HOME') }}/.ssh/google_compute_engine"
    ansible_python_interpreter: python
    gcp_project: "infra-27411228"
    gcp_cred_kind: serviceaccount
    gcp_cred_file: ../../credentials.json
  tasks:
    - name: create a instance
      gcp_compute_instance:
        name: "malecula"
        machine_type: n1-standard-1
        zone: us-central1-a
        project: test_project
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_cred_file }}"
        state: present
