---
  - name: Create
    hosts: localhost
    connection: local
    gather_facts: False
    no_log: false
    vars:
      molecule_file: "{{ lookup('env', 'MOLECULE_FILE') }}"
      molecule_instance_config: "{{ lookup('env', 'MOLECULE_INSTANCE_CONFIG') }}"
      molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
      ssh_port: 22
      ssh_user: "{{ lookup('env', 'USER') }}"
      ssh_identity_file: "{{ lookup('env', 'HOME') }}/.ssh/google_compute_engine"
      ansible_python_interpreter: python
      gcp_project: infra-27411228
      gcp_cred_file: "{{ lookup('env', 'GCE_CREDENTIALS_FILE') }}"

    tasks:
      - name: CREATE A INSTANCE
        gcp_compute_instance:
          name: "{{ item.name }}"
          machine_type: "{{ item.machine_type }}"
          disks:
          - auto_delete: 'true'
            boot: 'true'
            initialize_params:
              disk_size_gb: "{{ item.disk_size_gb }}"
              source_image: "{{ item.source_image }}"
          labels:
            environment: molecule
          network_interfaces:
          - network:
            access_configs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
          zone: "{{ item.zone }}"
          project: "{{ gcp_project }}"
          auth_kind: serviceaccount
          service_account_file: "{{ gcp_cred_file }}"
          state: present
        register: hosts
        with_items: "{{ molecule_yml.platforms }}"

      - name: GENERATE instance_config.yml
        template:
          src: instance_config.yml.j2
          dest: "{{ molecule_instance_config }}"
