---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: false
  vars:
    ssh_port: 22
    ssh_user: "travis"
    ssh_identity_file: "{{ lookup('env', 'HOME') }}/.ssh/google_compute_engine"
    ansible_python_interpreter: python
  tasks:
    - name: create a disk
      gcp_compute_disk:
        name: disk-instance
        size_gb: 50
        source_image: ubuntu-1604-xenial-v20200407
        zone: europe-west1-b
        project: "{{ lookup('env', 'GCE_PROJECT_ID') }}"
        auth_kind: "serviceaccount"
        service_account_file: "{{ lookup('env', 'GCE_CREDENTIALS_FILE') }}"
        state: present
      register: disk
