---
- name: Create
  hosts: all
  connection: local
  gather_facts: false
#  no_log: "{{ molecule_no_log }}"
  vars:
    ssh_port: 22
    ssh_user: "{{ lookup('env', 'USER') }}"
    ssh_identity_file: "{{ lookup('env', 'HOME') }}/.ssh/google_compute_engine"
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: create a disk
      gcp_compute_disk:
        name: disk-instance
        size_gb: 50
        source_image: ubuntu-1604-xenial-v20200407
        zone: europe-west1-b
        project: "{{ lookup('env', 'GCE_PROJECT_ID') }}"
        auth_kind: "serviceaccount"
        service_account_file: "{{ lookup('env', 'GCE_CREDENTIALS_FILE') }}"
        state: present
      register: disk

    - name: create a network
      gcp_compute_network:
        name: network-instance
        project: "{{ lookup('env', 'GCE_PROJECT_ID') }}"
        auth_kind: "serviceaccount"
        service_account_file: "{{ lookup('env', 'GCE_CREDENTIALS_FILE') }}"
        state: present
      register: network

    - name: create a address
      gcp_compute_address:
        name: address-instance
        region: europe-west1
        project: "{{ lookup('env', 'GCE_PROJECT_ID') }}"
        auth_kind: "serviceaccount"
        service_account_file: "{{ lookup('env', 'GCE_CREDENTIALS_FILE') }}"
        state: present
      register: address
