---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: false
  vars:
    ssh_port: 22
    ssh_user: "travis"
    ssh_identity_file: "{{ lookup('env', 'HOME') }}/.ssh/google_compute_engine"
    ansible_python_interpreter: python
    gcp_project: "{{ lookup('env', 'GCE_PROJECT_ID') }}"
    gcp_cred_kind: serviceaccount
    gcp_cred_file: "~/.secrets/credentials.json"
  tasks:
    - name: create a disk
      gcp_compute_disk:
        name: "{{ item.name }}"
        size_gb: 10
        source_image: "{{ item.image }}"
        zone: "{{ item.zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: disk
      with_items: "{{ molecule_yml.platforms }}"

    - name: create a instance
      gcp_compute_instance:
        name: "{{ item.name }}"
        machine_type: "{{ item.machine_type }}"
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        labels:
          environment: testing
        zone: "{{ item.zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      with_items: "{{ molecule_yml.platforms }}"
