---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: false
  vars:
    ssh_port: 22
    ssh_user: "travis"
    ssh_identity_file: "{{ lookup('env', 'HOME') }}/.ssh/google_compute_engine"
    ansible_python_interpreter: python
    gcp_project: "{{ lookup('env', 'GCE_PROJECT_ID') }}"
    gcp_cred_kind: serviceaccount
    gcp_cred_file: "~/.secrets/credentials.json"
  tasks:
    - name: create a disk
      gcp_compute_disk:
        name: "instance-travis"
        size_gb: 10
        source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20200407
        zone: europe-west1-b
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: disk

    - name: create a network
      gcp_compute_network:
          name: 'network-instance'
          project: "{{ gcp_project }}"
          auth_kind: "{{ gcp_cred_kind }}"
          service_account_file: "{{ gcp_cred_file }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          state: present
      register: network

    - name: create a address
      gcp_compute_address:
        name: address-instance
        region: europe-west1
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: address

    - name: create a instance
      gcp_compute_instance:
        name: "instance-travis"
        machine_type: f1-micro
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        labels:
          environment: testing
        network_interfaces:
        - network: "{{ network }}"
          access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
        zone: europe-west1-b
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_cred_file }}"
        state: present
