---
dependency:
  name: galaxy
  enabled: False
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: instance-travis
    project: infra-27411228
    zone: europe-west1-b
    machine_type: f1-micro
    source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20200407
    disk_size_gb: 10
  - name: instance-travis2
    project: infra-27411228
    zone: europe-west1-b
    machine_type: f1-micro
    source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20200407
    disk_size_gb: 10
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
 name: default
verifier:
  name: testinfra
  lint:
    name: flake8
